# プロジェクト名
name: WishList
# バンドルID
options:
  # バンドルプレフィックス
  bundleIdPrefix: WishList
  # LocalizationsのDevelopment Languageを指定
  developmentLanguage: ja
    
# ターゲットごとの設定
targets:
  WishList:
    # ターゲットの製品タイプ
    type: application
    # ターゲットのプラットフォーム
    platform: iOS
    # デプロイメントターゲット
    deploymentTarget: "17.0"
    #採用するfirebaseのサービス
      
    sources:
      - WishList
      - project.yml
      - .gitignore
      - .swiftlint.yml
      - .swift-version
      
    settings:
      base:
        MARKETING_VERSION: $(CURRENT_PROJECT_VERSION)
        CURRENT_PROJECT_VERSION: 1
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        DEVELOPMENT_TEAM: Chanchrons
        OTHER_LDFLAGS:
          - $(inherited)
          - -ObjC
          - -all_load

    info:
      path: WishList/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UILaunchScreen: ""
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        UISupportedInterfaceOrientations~iphone:
          [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UISupportedInterfaceOrientations~ipad:
          [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
